### ISSUE TITLE
Error when running 01-environment-setup.ps1

### ISSUE THREAD

**Issue by davidaascorreia** [microsoft/MCW-Azure-Synapse-Analytics-and-AI#54]
Hi

I have followed the environment setup successfully.

But when running the PowerShell script "01-environment-setup.ps1" from Cloud Shell, I get the following errors.. Can you please help? I tried deleting everything and doing the setup again, but still did not work.

Error below:

"

CLIInternalError: The command failed with an unexpected error. Here is the traceback:
'Response' object has no attribute 'status'
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/adal_authentication.py", line 103, in set_token
    super(MSIAuthenticationWrapper, self).set_token()
  File "/opt/az/lib/python3.6/site-packages/msrestazure/azure_active_directory.py", line 598, in set_token
    self.scheme, _, self.token = get_msi_token(self.resource, self.port, self.msi_conf)
  File "/opt/az/lib/python3.6/site-packages/msrestazure/azure_active_directory.py", line 486, in get_msi_token
    result.raise_for_status()
  File "/opt/az/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http://localhost:50342/oauth2/token

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 215, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 654, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 718, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 711, in _run_job
    six.reraise(*sys.exc_info())
  File "/opt/az/lib/python3.6/site-packages/six.py", line 703, in reraise
    raise value
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 688, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 325, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 784, in default_command_handler
    return op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/profile/custom.py", line 75, in get_access_token
    creds, subscription, tenant = profile.get_raw_token(subscription=subscription, resource=resource, tenant=tenant)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/_profile.py", line 644, in get_raw_token
    creds = self._get_token_from_cloud_shell(resource)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/_profile.py", line 392, in _get_token_from_cloud_shell
    auth = MSIAuthenticationWrapper(resource=resource)
  File "/opt/az/lib/python3.6/site-packages/msrestazure/azure_active_directory.py", line 592, in __init__
    self.set_token()
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/adal_authentication.py", line 114, in set_token
    .format(err.response.status, err.response.reason))
AttributeError: 'Response' object has no attribute 'status'
To open an issue, please run: 'az feedback'
CLIInternalError: The command failed with an unexpected error. Here is the traceback:
'Response' object has no attribute 'status'
Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/adal_authentication.py", line 103, in set_token
    super(MSIAuthenticationWrapper, self).set_token()
  File "/opt/az/lib/python3.6/site-packages/msrestazure/azure_active_directory.py", line 598, in set_token
    self.scheme, _, self.token = get_msi_token(self.resource, self.port, self.msi_conf)
  File "/opt/az/lib/python3.6/site-packages/msrestazure/azure_active_directory.py", line 486, in get_msi_token
    result.raise_for_status()
  File "/opt/az/lib/python3.6/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http://localhost:50342/oauth2/token

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/az/lib/python3.6/site-packages/knack/cli.py", line 215, in invoke
    cmd_result = self.invocation.execute(args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 654, in execute
    raise ex
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 718, in _run_jobs_serially
    results.append(self._run_job(expanded_arg, cmd_copy))
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 711, in _run_job
    six.reraise(*sys.exc_info())
  File "/opt/az/lib/python3.6/site-packages/six.py", line 703, in reraise
    raise value
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 688, in _run_job
    result = cmd_copy(params)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/commands/__init__.py", line 325, in __call__
    return self.handler(*args, **kwargs)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/__init__.py", line 784, in default_command_handler
    return op(**command_args)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/command_modules/profile/custom.py", line 75, in get_access_token
    creds, subscription, tenant = profile.get_raw_token(subscription=subscription, resource=resource, tenant=tenant)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/_profile.py", line 644, in get_raw_token
    creds = self._get_token_from_cloud_shell(resource)
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/_profile.py", line 392, in _get_token_from_cloud_shell
    auth = MSIAuthenticationWrapper(resource=resource)
  File "/opt/az/lib/python3.6/site-packages/msrestazure/azure_active_directory.py", line 592, in __init__
    self.set_token()
  File "/opt/az/lib/python3.6/site-packages/azure/cli/core/adal_authentication.py", line 114, in set_token
    .format(err.response.status, err.response.reason))
AttributeError: 'Response' object has no attribute 'status'
To open an issue, please run: 'az feedback'
Invoke-RestMethod: /home/david/Synapse-MCW/Hands-on lab/environment-setup/automation/environment-automation/environment-automation.psm1:1446
Line |
1446 |  …   $result = Invoke-RestMethod  -Uri $uri -Method $method -Body $body  …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | {"code":"BearerTokenNotFound","message":"BearerToken not found in request"}

Invoke-RestMethod: /home/david/Synapse-MCW/Hands-on lab/environment-setup/automation/environment-automation/environment-automation.psm1:1446
Line |
1446 |  …   $result = Invoke-RestMethod  -Uri $uri -Method $method -Body $body  …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | {"code":"BearerTokenNotFound","message":"BearerToken not found in request"}

Invoke-RestMethod: /home/david/Synapse-MCW/Hands-on lab/environment-setup/automation/environment-automation/environment-automation.psm1:1446
Line |
1446 |  …   $result = Invoke-RestMethod  -Uri $uri -Method $method -Body $body  …
     |                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | {"code":"BearerTokenNotFound","message":"BearerToken not found in request"}

"

**Comment by codingbandit** [comment]
Please ensure you are running all scripts using the cloud shell.

**Comment by codingbandit** [comment]
I was able to run through the setup successfully, including 01-environment-setup.ps1. I have a couple of questions.

1. When you did the az login step, and returned to the cloud console window, did you see output similar to the following [indicates a successful az login]?

![image](https://user-images.githubusercontent.com/3979478/98951247-fefcbc00-24c7-11eb-814b-efc04167839e.png)

2. Do you know if there may be security restrictions in place on your account that may prevent running REST calls from the cloud console?

**Comment by davidaascorreia** [comment]
No, I received "Unexpected polling state interaction_required"

![image](https://user-images.githubusercontent.com/47411958/98953799-6bde7900-24fd-11eb-8bc3-c4a45e083ca7.png)

I do see my subscriptions when using "az account list" the way you demonstrate above.

I can ask my IT department if I have any restrictions on the cloud console.

**Comment by codingbandit** [comment]
This process definitely requires you to be able to do the device login - so this is definitely the problem. I will see if any of my connections have seen this error before. Are you prompted with the code form when clicking on the device login link as shown in the lab guidance ?

**Comment by codingbandit** [comment]
In doing a quick search - it seems like it could be relevant to cached credentials, or something to do with MFA. 

https://github.com/Azure/azure-cli/issues/6095

Could you try an in-private browser, and log in to the azure portal there. And as a last resort, maybe try using a non-chromium based browser such as firefox [hoping the former gets you where you need to go!]

**Comment by davidaascorreia** [comment]
The latter worked; in-private browser. Thanks!

**Comment by timahenning** [comment]
Solution provided.
